version: '3.7'

services:

  www:
    container_name: www
    build:
      context: ./www
      dockerfile: Dockerfile
    volumes:
      - './www:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
  api:
    depends_on:
      - db
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - './api:/app'
      - '/app/node_modules'
    ports:
      - '3030:8080'
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'p4ssw0rd'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'p4ssword'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mind-db:/var/lib/mysql
    # Names our volume
volumes:
  mind-db:
