# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
# If you are building your code for production
# RUN npm ci --only=production
RUN npm install @vue/cli@3.7.0 -g
RUN npm install vuetify

# start app
CMD ["npm", "run", "serve"]