openapi: 3.0.0
info:
  title: 'Mind Courses API'
  description: This is an API for Courses developed in mind
  version: 2.0.0
servers:
  - url: http://localhost:3030/api/v1
    description: Development server version 1
  - url: http://localhost:3030/api/v2
    description: Development server version 2
paths:
  /roles:
    get:
      summary: Retrieve all roles
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user roles
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object